spring:

  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/flowershop
    username: root
    password: Thientho2205
=======
    url: jdbc:mysql://localhost:3307/flowershop
    username: root
    password: 123456
>>>>>>> origin/master
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: sktththien@gmail.com
    password: gvjr jukj ovrh uvrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  main:
    web-application-type: servlet

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
<<<<<<< HEAD
        expiration: 604800000
=======
        expiration: 604800000

server:
  port: 8080
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 11032003
    key-store-type: PKCS12
    key-alias: localhost
>>>>>>> origin/master
